FileVersion = 1

[Project]
Name = "Detex"
TargetType = "BeefLib"
StartupObject = "Detex.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/dist/Win64/Debug/lib/Detex.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/Win64/Debug/bin/*.dll\")"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/dist/Win64/Release/lib/Detex.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/Win64/Release/bin/*.dll\")"]
